from .box_geometry import BoxGeometry
from .circle_geometry import CircleGeometry
from .cylinder_geometry import CylinderGeometry
from .cone_geometry import ConeGeometry
from .sphere_geometry import SphereGeometry
from .plane_geometry import PlaneGeometry
from .torus_geometry import TorusGeometry
from .torus_knot_geometry import TorusKnotGeometry
from .lathe_geometry import LatheGeometry
from .polyhedron_geometry import PolyhedronGeometry
from .dodecahedron_geometry import DodecahedronGeometry
from .icosahedron_geometry import IcosahedronGeometry
from .octahedron_geometry import OctahedronGeometry
from .tetrahedron_geometry import TetrahedronGeometry